# These are supported funding model platforms

github: [gappleto97]
custom: ["https://www.blockchain.com/eth/address/0xDb7FD6A1eDeA6E46fF9A9AdD0De4dFd6aCD5fBD2", "https://www.blockchain.com/btc/address/1CPHXRn8SYQYTxSgXFESG28WrwXKbb69HU", "https://www.blockchain.com/bch/address/1CPHXRn8SYQYTxSgXFESG28WrwXKbb69HU"]
